######################################################################
# Automatically generated by qmake (2.01a) Fr. Jun 4 16:31:06 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += convert.h
SOURCES += convert.cpp main.cpp
